### ISSUE TITLE
Choose pathways as test cases

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/network-ptm-integration#1]
Let's pick one or a handful of pathways to use as test cases and compose a `pathways.tsv` file listing the WPIDs per row. These should be CPTAC-related pathways that we understand well and can manually verify and interpret the final output without too much trouble.

For example, we might pick a pathway that has been manually annotated with PTMs already. Then we could used a "stripped" version as the input to this new pipeline and compare it with the manual version. It shouldn't necessarily be the same, but the manual work already done can help in evaluating the output.

**Comment by khanspers** [comment]
Making a list here for now:
[Hippo-Merlin signaling dysregulation](https://www.wikipathways.org/pathways/WP4541.html) 
[Wnt Signaling](https://www.wikipathways.org/pathways/WP428.html) 
[Cell Cycle](https://www.wikipathways.org/pathways/WP179.html)
[ErbB signaling pathway](https://www.wikipathways.org/pathways/WP673.html)
[TCA cycle nutrient use and invasiveness of ovarian cancer](https://www.wikipathways.org/pathways/WP2868.html) - would be nice if we could get a dataset with both low and high invasiveness ovarian cancer.

**Comment by khanspers** [comment]
For now, we are using specific pathways corresponding to [PROGENy pathway activity](https://www.nature.com/articles/s41467-017-02391-6).
