### ISSUE TITLE
PTM annotations

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/network-ptm-integration#2]
Presuming we'll use Phosphosite plus, let's take a moment to catalog the download/API options they provide and see what would be most useful. @khanspers has probably already done this, but it would be good to capture this knowledge in a document.

For example, in this repo, we should collect the annotation files we think will be useful into a folder called `annotations` and add a README with a brief description of the files.

**Comment by khanspers** [comment]
The PSP annotation files are available under [Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported (CC BY-NC-SA 3.0)](https://creativecommons.org/licenses/by-nc-sa/3.0/). It does say that we are free to "Share — copy and redistribute the material in any medium or format", so maybe its ok to add the files to this repo? 

However, what about this ShareAlike statement in regard to incorporating sites on pathways:

"ShareAlike — If you remix, transform, or build upon the material, you must distribute your contributions under the [same license](https://creativecommons.org/licenses/by-nc-sa/3.0/#) as the original." 

-> Is this a problem in terms of our CC0 license for pathways?

**Comment by AlexanderPico** [comment]
> The PSP annotation files are available under [Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported (CC BY-NC-SA 3.0)](https://creativecommons.org/licenses/by-nc-sa/3.0/). It does say that we are free to "Share — copy and redistribute the material in any medium or format", so maybe its ok to add the files to this repo?
> 
> However, what about this ShareAlike statement in regard to incorporating sites on pathways:
> 
> "ShareAlike — If you remix, transform, or build upon the material, you must distribute your contributions under the [same license](https://creativecommons.org/licenses/by-nc-sa/3.0/#) as the original."
> 
> -> Is this a problem in terms of our CC0 license for pathways?

Not a problem

**Comment by AlexanderPico** [comment]
Let's catalog the download/API options they provide and see what would be most useful and document it here. We don't need to actually download everything and host it here; that's not the plan.

**Comment by khanspers** [comment]
**Files from [PSP download](https://www.phosphosite.org/staticDownloads):**

1. Kinase_Substrate_Dataset
2. Phosphorylation_site_dataset
3. Regulatory_sites

**Kinase-substrate dataset**
_Information from PSP: experimentally determined substrates, sequences, cognate kinases, and metadata curated from the literature_

=> Relevant columns: all. Includes domain info, and two columns IN_VIVO_RXN and IN_VITRO_RXN to designate evidence type, (mostly) matching "Putative in vivo kinses" and "Kinase, in vitro" from Upstream tab. 
Example filter for "SUBSTRATE=Akt1", "KIN_ORGANISM=human" results in 41.

**Phosphorylation_site_dataset**
_Information from PSP: sequences surrounding the PTMs (+/- 7 AAs), gene symbols, accession IDs, site group IDs, molecular weights, number of associated records, and Cell Signaling Technology catalog numbers where available. Separate files for each modification type including phosphorylation, acetylation, ubiquitination, methylation, O-glycosylation, sumoylation, etc._

=> This is the same information as the Site Table (for example https://www.phosphosite.org/proteinAction.action?id=570&showAllSites=true)
Relevant columns: GENE, PROTEIN, GENE_ID, ACC_ID, MOD-RSD, SITE_GRP_ID, ORGANISM, DOMAIN, SITE
Example filter for "GENE=AKT1", "ORGANISM=human", "MOD-RSD includes -p" results in 35 entries.

**Regulatory_sites**
_Information from PSP: Information curated from the literature about modification sites shown to regulate molecular functions, biological processes, and molecular interactions including protein-protein interactions._

=> Subset of sites from Site Table (for example https://www.phosphosite.org/proteinAction.action?id=570&showAllSites=true)
Relevant columns: GENE, PROTEIN, ACC_ID, GENE_ID, MOD-RSD, SITE_GRP_ID, ORGANISM, DOMAIN, SITE
Example filter for "GENE=AKT1", "ORGANISM=human", "MOD-RSD includes -p" results in 17 entries.
