### ISSUE TITLE
PTM datasets

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/network-ptm-integration#3]
@khanspers and Bing are collecting PTM datasources. Let's capture that table here in folder called `datasets`, as a README, along with some sample datasets.

At first, let's get our hands on a few datasets that will likely relate to the handful of test pathways we have selected (see #1)

**Comment by AlexanderPico** [comment]
From Sarah: CPTAC pancancer, harmonizing 10 cancer datasets.
https://kb.linkedomics.org/download

**Comment by AlexanderPico** [comment]
Yuxing will send correlated [PROGENy](https://saezlab.github.io/progeny/
):EGFR and pathway activity score (linear model) values per phosphosite.

**Comment by khanspers** [comment]
From Yuxing we got the following:

CPTAC_phospho_tn.txt (The p-values and statistics (“val”) are from Wilcoxon rank sum test. Positive values mean abundance is higher in tumor.)
CPTAC_protein_tn.txt (The p-values and statistics (“val”) are from Wilcoxon rank sum test. Positive values mean abundance is higher in tumor.)
CPTAC_PROGENy__EGFR.txt (EGFR pathway set correlation from PROGENy. The cohort.val is the Spearman correlation coefficient and cohort.pval is the p-value)
